name: spa
description: Solar Position Algorithm used for finding the orientation of the sun at any point on earth.
version: 1.3.0
homepage: https://github.com/PixelToast/dart-spa

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  meta: ^1.9.1
  tuple: ^2.0.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.3
