name: cities
description: Cities example for the spa plugin
version: 1.0.0
homepage: https://github.com/PixelToast/dart-spa
publish_to: none

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  timezone: ^0.9.2
  spa:
    path: ../../

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.3
